WebApplication/Controllers/AvailabilityController.cs
using BLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace WebApplication.Controllers
{
    public class AvailabilityController : Controller
    {
        private IConfiguration Configuration { get; }
        public AvailabilityController(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        //Allows the administrator to reset availability of every delivery employee.
        public IActionResult Reset()
        {
            AvailibilityManager aManager = new AvailibilityManager(Configuration);
            aManager.ResetAvailability();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.userType = HttpContext.Session.GetInt32("userType");
            return View();
        }
        
    }
}

WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["User"] = ViewBag.username;
}

    <div class="row">
        @if (ViewBag.userType == 0)
        {
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="~/images/resized_kotturoti.jpg" alt="ASP.NET" class="img-responsive" />
                    </div>

                </div>
            </div>
            <div class="col-md-8">
                <h2>How it works</h2>
                <ul>
                    <li>Select a City in the tab "order something"</li>
                    <li>Then you will see the restaurant of the city</li>
                    <li>Select a Restaurant</li>
                    <li>Then you will see the dishes of the restaurant</li>
                    <li>Select one or many dishes, it will brings you to the cart.</li>
                    <li>Then you proceed to checkout and confirm your order by selecting a delivery time.</li>
                    <li>You can see all your orders in "My order" tab and cancel an order if there are still 3 hours remaining to the delivery time.</li>
                    <li>Logout using the tab "username, logout?"</li>
                </ul>
            </div>

        }
        @if (ViewBag.userType == 2)
        {
            <br/>
            <a href="@Url.Action("Reset", "Availability")" class="btn btn-warning">Reset Availabilites of delivery employees</a>

        }
    </div>