WebApplication/Models/dishes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dishes
    {
        public dishes()
        {
            this.dishes_order = new HashSet<dishes_order>();
        }
    
        public int idDishes { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string status { get; set; }
        public int idRestaurant { get; set; }
    

        public virtual ICollection<dishes_order> dishes_order { get; set; }
        public virtual restaurants restaurants { get; set; }
    }
}

WebApplication/Models/restaurants.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurants
    {
        public restaurants()
        {
            this.dishes = new HashSet<dishes>();
        }
    
        public int idRestaurant { get; set; }
        public string merchant_name { get; set; }
        public string createdAt { get; set; }
        public int idCity { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual ICollection<dishes> dishes { get; set; }
    }
}

WebApplication/Controllers/CitiesController.cs
using System.Collections.Generic;
using BLL;
using DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebApplication.Helpers;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class CitiesController : Controller
    {
        private IConfiguration Configuration { get; }
        public CitiesController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        //Display cities in our Network
        public ActionResult Index()
        {
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.userType = HttpContext.Session.GetInt32("userType");
            CitiesManager cManager = new CitiesManager(Configuration);
            return View(cManager.GetCities());
        }

        //Display restaurants of our network in the selected city
        public ActionResult Restaurants(int id)
        {
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.userType = HttpContext.Session.GetInt32("userType");
            RestaurantManager rManager = new RestaurantManager(Configuration);
            return View(rManager.GetRestaurantsOfCity(id));
        }

        //Display dishes served by the selected restaurant
        public ActionResult Dishes(int id)
        {
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.userType = HttpContext.Session.GetInt32("userType");
            DishesManager dManager = new DishesManager(Configuration);
            return View(dManager.GetDishesOfRestaurant(id));
        }

        //Allows customer to add a dish to his cart
        public ActionResult AddToCart(int id)
        {
            //We retrieve the dishe's price
            DishesManager dManager = new DishesManager(Configuration);
            Dishes dishe = new Dishes();
            int price = dManager.GetDishePrice(id);

            //We add the price to the total amount, we initiate the session value if it is the first dish of the cart.
            if (HttpContext.Session.GetInt32("TotalAmount") != null) {

                HttpContext.Session.SetInt32("TotalAmount", (price + (int)HttpContext.Session.GetInt32("TotalAmount")));
            }
            else
            {
                HttpContext.Session.SetInt32("TotalAmount", price );
            }
            //So if it is the first dish to be added we create a list of item(Dishe+quantity) in the session
            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Dishe = dManager.GetDishe(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {   /*Else if the list is already created we get it and check if the dish is already in the list.
                    If yes we increment the quantity, else we add the dish as a new item.
                 */
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = DoesExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Dishe = dManager.GetDishe(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            //Redirect to the cart
            return RedirectToAction("Index", "Cart");
        }

        //Go through the list of item and try to match the id with an existing dish
        private int DoesExist(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Dishe.idDishes.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        
    }
}

WebApplication/Controllers/CredentialsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using DTO;
using BLL;
using Microsoft.AspNetCore.Http;

namespace WebApplication.Controllers
{
    public class CredentialsController : Controller
    {
        private IConfiguration Configuration { get; }

        public CredentialsController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        //Clear the session, we use it to logout and also to login with new credentials
        [HttpGet]
        public IActionResult Index()
        {
            HttpContext.Session.Clear();
            return View();
        }

        //When the page receive credentials, we check them with those in the DB.
        [HttpPost]
        public ActionResult Index(Credentials credModel)
        {
            string usernameC = credModel.username;
            string passwordC = credModel.password;

            var credentialsDbManager = new CredentialsManager(Configuration);
            int idUserTryingToConnect = credentialsDbManager.GetIdCredentials(usernameC);
            int userStatus = credentialsDbManager.GetStatus(usernameC);
            //Get password using 
            if (passwordC == credentialsDbManager.GetPassword(usernameC))
            {
                HttpContext.Session.SetString("username", usernameC);
                HttpContext.Session.SetInt32("id", idUserTryingToConnect);
                HttpContext.Session.SetInt32("userType", userStatus);
                //status 2 means admin, 1=Delivery employee, 0 = customer
                //The view the user will see depends on his status in our DB
                if (userStatus == 2)
                {
                    return RedirectToAction("Index", "Home");
                }

                else if (userStatus == 1)
                {
                    StaffManager sManager = new StaffManager(Configuration);
                    int idStaff = sManager.GetStaffId(idUserTryingToConnect);
                    HttpContext.Session.SetInt32("idStaff", idStaff);
                    return RedirectToAction("Index", "DishesOrder");
                }
                else if (userStatus == 0)
                {
                    CustomerManager cManager = new CustomerManager(Configuration);
                    HttpContext.Session.SetInt32("idCustomer", cManager.GetCustomerIDByCredentials(idUserTryingToConnect));
                    return RedirectToAction("Index", "Home");
                }
                //If we did find a username and password but not a status we through an error.
                return RedirectToAction("LoginError", "Error", new { message = "Your account is not correctly initialized. Please contact our support : support@vdeat.ch or connect with another account." });
            }
            else
            {   //If the credentials did not match we through an error
                return RedirectToAction("LoginError", "Error", new { message = "Unfortunately your username or password did not match our records. Please try again." });
            }
        }
    }
}

WebApplication/Views/Shared/Dishes.cshtml
@model IEnumerable<DTO.Dishes>

@{
    ViewData["Title"] = "Index";
}
<!--Shared view displaying all the dishes of a given restaurant-->

<h2>Dishes of the restaurant</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)
                </td>

                <td>
                    @Html.ActionLink("AddToCart", "AddToCart", new { id = item.idDishes })
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication/Views/Shared/Restaurants.cshtml
@model IEnumerable<DTO.Restaurant>

@{
    ViewData["Title"] = "Restaurants";
}

<!--Shared view displaying all the restaurants of a given city-->

<h2>List of restaurants of the city</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Restaurant
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.merchant_name)
                </td>
                <td>
                    @Html.ActionLink("See Dishes", "Dishes", new { id = item.idRestaurant })
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication/Views/Shared/_Layout.cshtml
<!--Shared view displaying the navbar + footer-->

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Vaud Eat</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Vaud Eat</a>
            </div>
            @if (ViewBag.userType == 0)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Cities" asp-action="Index">Order Something</a></li>
                        <li><a asp-area="" asp-controller="Cart" asp-action="Index">Cart</a></li>
                        <li><a asp-area="" asp-controller="DishesOrder" asp-action="CustomerOrders">My Orders</a></li>
                        <li> <a asp-area="" asp-controller="Credentials" asp-action="Index">Logout, @Html.Raw(ViewBag.username)?</a></li>
                    </ul>
                </div>
            }
            @if (ViewBag.userType == 1)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="DishesOrder" asp-action="Index">To Deliver</a></li>
                        <li> <a asp-area="" asp-controller="Credentials" asp-action="Index">Logout, @Html.Raw(ViewBag.username)?</a></li>
                    </ul>
                </div>
            }
            @if (ViewBag.userType == 2)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li> <a asp-area="" asp-controller="Credentials" asp-action="Index">Logout, @Html.Raw(ViewBag.username)?</a></li>
                    </ul>
                </div>
            }
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - VaudEat</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_Logged.cshtml
@{
    ViewData["Title"] = "_Logged";
}

    <li></li>